# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:59
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='geom',
            field=djgeojson.fields.PointField(default='POINT'),
        ),
    ]
