# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0002_marker_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='location',
        ),
        migrations.AlterField(
            model_name='marker',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
