# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0003_auto_20171117_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
