# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0004_marker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
