# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 14:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0005_marker_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Polygone',
            },
        ),
    ]
